name: publish npm

on:
  push:
    paths:
      - 'dist/package.json'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --unshallow
      
      - name: Check for changes in package.json
        id: package-changed
        run: |
          git diff --exit-code --quiet ${{ github.event.before }} ${{ github.sha }} -- package.json
          if [ $? -eq 1 ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
          fi

      - name: Setup Node.js
        if: steps.package-changed.outputs.changed == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org

      - name: Publish to npm
        if: steps.package-changed.outputs.changed == 'true'
        run: npm publish --access public
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
